export const LIST_SURAT_GLOBAL = [
  {
    id: 1,
    code: "A04",
    name: "Surat Keterangan Domisili",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 2,
    code: "A01",
    name: "Surat Keterangan Usaha",
    desc: "KTP, KK, data usaha",
    type: "Manual",
  },
  {
    id: 3,
    code: "A02",
    name: "Surat Keterangan Tidak Memiliki Rumah",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 4,
    code: "A03",
    name: "Surat Keterangan Penghasilan",
    desc: "KTP, KK, data penghasilan",
    type: "Manual",
  },
  {
    id: 5,
    code: "A05",
    name: "Surat Keterangan Tidak Mampu",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 6,
    code: "A06",
    name: "Surat Keterangan Beda Nama",
    desc: "KTP, KK, dokumen pendukung",
    type: "Manual",
  },
  {
    id: 7,
    code: "A07",
    name: "Surat Keterangan Penguburan",
    desc: "Surat kematian, KK",
    type: "Manual",
  },
  {
    id: 8,
    code: "A08",
    name: "Surat Keterangan Kelahiran",
    desc: "Surat lahir, KK",
    type: "Manual",
  },
  {
    id: 9,
    code: "A09",
    name: "Surat Keterangan Belum Menikah",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 10,
    code: "AC01",
    name: "Surat Keterangan Pengantar Permohonan SKCK",
    desc: "KK",
    type: "Document",
  },
  {
    id: 11,
    code: "C01",
    name: "Pernyataan Tanggung Jawab Acara",
    desc: "Dokumen pernyataan bertanda tangan",
    type: "Document",
  },
  {
    id: 12,
    code: "C02",
    name: "Persetujuan/Izin Lingkungan",
    desc: "Dokumen persetujuan warga",
    type: "Document",
  },
  
];