export const LIST_SURAT_GLOBAL = [
  {
    id: 1,
    code: "A04",
    name: "Surat Keterangan Domisili",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 2,
    code: "A01",
    name: "Surat Keterangan Usaha",
    desc: "KTP, KK, data usaha",
    type: "Manual",
  },
  {
    id: 3,
    code: "A09",
    name: "Surat Keterangan Belum Menikah",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 4,
    code: "A05",
    name: "Surat Keterangan Tidak Mampu",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 5,
    code: "A02",
    name: "Surat Keterangan Tidak Memiliki Rumah",
    desc: "KTP, KK",
    type: "Manual",
  },
  {
    id: 6,
    code: "A03",
    name: "Surat Keterangan Penghasilan",
    desc: "KTP, KK, bukti penghasilan",
    type: "Manual",
  },
  {
    id: 7,
    code: "A06",
    name: "Surat Keterangan Beda Nama",
    desc: "KTP, KK, dokumen nama",
    type: "Manual",
  },
  {
    id: 8,
    code: "A07",
    name: "Surat Keterangan Penguburan",
    desc: "KTP, KK, surat kematian",
    type: "Manual",
  },
  {
    id: 9,
    code: "A08",
    name: "Surat Keterangan Kelahiran",
    desc: "KTP, KK, akta kelahiran",
    type: "Manual",
  },
  {
    id: 10,
    code: "A10",
    name: "Surat Keterangan & Pertama Kali Memiliki Rumah",
    desc: "KTP, KK, bukti kepemilikan rumah",
    type: "Manual",
  },
];
