export const LIST_SURAT_GLOBAL = [
  {
    id: 1,
    code: "SKD",
    name: "Surat Keterangan Domisili",
    desc: "KK",
    type: "Auto",
  },
  {
    id: 2,
    code: "SKU",
    name: "Surat Keterangan Usaha",
    desc: "KK",
    type: "Manual",
  },
  {
    id: 3,
    code: "SKTMR",
    name: "Surat Keterangan Tidak Memiliki Rumah",
    desc: "KK",
    type: "Document",
  },
  {
    id: 4,
    code: "SKP",
    name: "Surat Keterangan Penghasilan",
    desc: "KK",
    type: "Auto",
  },
  {
    id: 5,
    code: "SKTM",
    name: "Surat Keterangan Tidak Mampu",
    desc: "KK",
    type: "Manual",
  },
  {
    id: 6,
    code: "SKBN",
    name: "Surat Keterangan Beda Nama",
    desc: "Ijazah",
    type: "Document",
  },
  {
    id: 7,
    code: "SKP",
    name: "Surat Keterangan Penguburan",
    desc: "KK, surat kematian",
    type: "Auto",
  },
  {
    id: 8,
    code: "SKTK",
    name: "Surat Keterangan Kelahiran",
    desc: "Surat kelahiran, KK",
    type: "Manual",
  },
  {
    id: 9,
    code: "SkiBM",
    name: "Surat Keterangan Belum Menikah",
    desc: "KK",
    type: "Document",
  },
];
